export type Gite = {
  id: string;
  ordre?: number;
  nom: string;
  prefixe_contrat: string;
  adresse_ligne1: string;
  adresse_ligne2?: string | null;
  capacite_max: number;
  proprietaires_noms: string;
  proprietaires_adresse: string;
  site_web?: string | null;
  email?: string | null;
  telephones: string[];
  taxe_sejour_par_personne_par_nuit: number;
  iban: string;
  bic?: string | null;
  titulaire: string;
  regle_animaux_acceptes: boolean;
  regle_bois_premiere_flambee: boolean;
  regle_tiers_personnes_info: boolean;
  options_draps_par_lit: number;
  options_linge_toilette_par_personne: number;
  options_menage_forfait: number;
  options_depart_tardif_forfait: number;
  options_chiens_forfait: number;
  heure_arrivee_defaut: string;
  heure_depart_defaut: string;
  caution_montant_defaut: number;
  cheque_menage_montant_defaut: number;
  arrhes_taux_defaut: number;
  prix_nuit_liste?: number[];
  caracteristiques?: string | null;
  contrats_count?: number;
  factures_count?: number;
  createdAt?: string;
  updatedAt?: string;
};

export type ContratOptions = {
  draps?: { enabled: boolean; nb_lits?: number; offert?: boolean };
  linge_toilette?: { enabled: boolean; nb_personnes?: number; offert?: boolean };
  menage?: { enabled: boolean; offert?: boolean };
  depart_tardif?: { enabled: boolean; offert?: boolean };
  chiens?: { enabled: boolean; nb?: number; offert?: boolean };
  regle_animaux_acceptes?: boolean;
  regle_bois_premiere_flambee?: boolean;
  regle_tiers_personnes_info?: boolean;
};

export type Contrat = {
  id: string;
  numero_contrat: string;
  gite_id: string;
  date_creation: string;
  date_derniere_modif: string;
  locataire_nom: string;
  locataire_adresse: string;
  locataire_tel: string;
  locataire_email?: string | null;
  nb_adultes: number;
  nb_enfants_2_17: number;
  date_debut: string;
  heure_arrivee: string;
  date_fin: string;
  heure_depart: string;
  nb_nuits: number;
  prix_par_nuit: number;
  remise_montant: number;
  taxe_sejour_calculee?: number;
  options: ContratOptions;
  arrhes_montant: number;
  arrhes_date_limite: string;
  solde_montant: number;
  caution_montant: number;
  cheque_menage_montant: number;
  afficher_caution_phrase: boolean;
  afficher_cheque_menage_phrase: boolean;
  clauses: Record<string, unknown>;
  pdf_path: string;
  statut_paiement_arrhes: "non_recu" | "recu";
  notes?: string | null;
  gite?: Gite;
};

export type Facture = {
  id: string;
  numero_facture: string;
  gite_id: string;
  date_creation: string;
  date_derniere_modif: string;
  locataire_nom: string;
  locataire_adresse: string;
  locataire_tel: string;
  nb_adultes: number;
  nb_enfants_2_17: number;
  date_debut: string;
  heure_arrivee: string;
  date_fin: string;
  heure_depart: string;
  nb_nuits: number;
  prix_par_nuit: number;
  remise_montant: number;
  taxe_sejour_calculee?: number;
  options: ContratOptions;
  arrhes_montant: number;
  arrhes_date_limite: string;
  solde_montant: number;
  caution_montant: number;
  cheque_menage_montant: number;
  afficher_caution_phrase: boolean;
  afficher_cheque_menage_phrase: boolean;
  clauses: Record<string, unknown>;
  pdf_path: string;
  statut_paiement: "non_reglee" | "reglee";
  notes?: string | null;
  gite?: Gite;
};
