export type Gestionnaire = {
  id: string;
  prenom: string;
  nom: string;
  gites_count?: number;
  createdAt?: string;
  updatedAt?: string;
};

export type Gite = {
  id: string;
  ordre?: number;
  nom: string;
  prefixe_contrat: string;
  adresse_ligne1: string;
  adresse_ligne2?: string | null;
  capacite_max: number;
  nb_adultes_max: number;
  nb_adultes_habituel: number;
  proprietaires_noms: string;
  proprietaires_adresse: string;
  site_web?: string | null;
  email?: string | null;
  airbnb_listing_id?: string | null;
  telephones: string[];
  taxe_sejour_par_personne_par_nuit: number;
  iban: string;
  bic?: string | null;
  titulaire: string;
  regle_animaux_acceptes: boolean;
  regle_bois_premiere_flambee: boolean;
  regle_tiers_personnes_info: boolean;
  options_draps_par_lit: number;
  options_linge_toilette_par_personne: number;
  options_menage_forfait: number;
  options_depart_tardif_forfait: number;
  options_chiens_forfait: number;
  heure_arrivee_defaut: string;
  heure_depart_defaut: string;
  caution_montant_defaut: number;
  cheque_menage_montant_defaut: number;
  arrhes_taux_defaut: number;
  prix_nuit_liste?: number[];
  caracteristiques?: string | null;
  gestionnaire_id?: string | null;
  gestionnaire?: Pick<Gestionnaire, "id" | "prenom" | "nom"> | null;
  contrats_count?: number;
  factures_count?: number;
  reservations_count?: number;
  createdAt?: string;
  updatedAt?: string;
};

export type IcalSource = {
  id: string;
  gite_id: string;
  type: string;
  url: string;
  include_summary?: string | null;
  exclude_summary?: string | null;
  is_active: boolean;
  ordre: number;
  createdAt?: string;
  updatedAt?: string;
  gite?: Pick<Gite, "id" | "nom" | "prefixe_contrat" | "ordre">;
};

export type ReservationPlaceholder = {
  id: string;
  abbreviation: string;
  label?: string | null;
  reservations_count: number;
};

export type Reservation = {
  id: string;
  gite_id?: string | null;
  placeholder_id?: string | null;
  origin_system?: "app" | "what-today" | "ical" | "pump" | "har" | "csv" | "legacy" | null;
  origin_reference?: string | null;
  export_to_ical?: boolean;
  airbnb_url?: string | null;
  hote_nom: string;
  telephone?: string | null;
  email?: string | null;
  date_entree: string;
  date_sortie: string;
  nb_nuits: number;
  nb_adultes: number;
  prix_par_nuit: number;
  prix_total: number;
  source_paiement?: string | null;
  commentaire?: string | null;
  remise_montant: number;
  commission_channel_mode?: "euro" | "percent" | null;
  commission_channel_value: number;
  frais_optionnels_montant: number;
  frais_optionnels_libelle?: string | null;
  frais_optionnels_declares: boolean;
  options?: ContratOptions;
  createdAt?: string;
  updatedAt?: string;
  gite?: Pick<Gite, "id" | "nom" | "prefixe_contrat" | "ordre">;
  placeholder?: Pick<ReservationPlaceholder, "id" | "abbreviation" | "label">;
};

export type ContratOptions = {
  draps?: { enabled: boolean; nb_lits?: number; prix_unitaire?: number; offert?: boolean; declared?: boolean };
  linge_toilette?: { enabled: boolean; nb_personnes?: number; offert?: boolean; declared?: boolean };
  menage?: { enabled: boolean; offert?: boolean; declared?: boolean };
  depart_tardif?: { enabled: boolean; prix_forfait?: number; offert?: boolean; declared?: boolean };
  chiens?: { enabled: boolean; nb?: number; offert?: boolean; declared?: boolean };
  regle_animaux_acceptes?: boolean;
  regle_bois_premiere_flambee?: boolean;
  regle_tiers_personnes_info?: boolean;
};

export type Contrat = {
  id: string;
  numero_contrat: string;
  gite_id: string;
  date_creation: string;
  date_derniere_modif: string;
  locataire_nom: string;
  locataire_adresse: string;
  locataire_tel: string;
  locataire_email?: string | null;
  nb_adultes: number;
  nb_enfants_2_17: number;
  date_debut: string;
  heure_arrivee: string;
  date_fin: string;
  heure_depart: string;
  nb_nuits: number;
  prix_par_nuit: number;
  remise_montant: number;
  taxe_sejour_calculee?: number;
  options: ContratOptions;
  arrhes_montant: number;
  arrhes_date_limite: string;
  solde_montant: number;
  caution_montant: number;
  cheque_menage_montant: number;
  afficher_caution_phrase: boolean;
  afficher_cheque_menage_phrase: boolean;
  clauses: Record<string, unknown>;
  pdf_path: string;
  pdf_sent_path?: string | null;
  date_envoi_email?: string | null;
  statut_reception_contrat: "non_recu" | "recu";
  date_reception_contrat?: string | null;
  statut_paiement_arrhes: "non_recu" | "recu";
  date_paiement_arrhes?: string | null;
  mode_paiement_arrhes?: "Chèque" | "Virement" | "Espèces" | "A définir" | null;
  notes?: string | null;
  reservation_id?: string | null;
  gite?: Gite;
};

export type Facture = {
  id: string;
  numero_facture: string;
  gite_id: string;
  date_creation: string;
  date_derniere_modif: string;
  locataire_nom: string;
  locataire_adresse: string;
  locataire_tel: string;
  locataire_email?: string | null;
  nb_adultes: number;
  nb_enfants_2_17: number;
  date_debut: string;
  heure_arrivee: string;
  date_fin: string;
  heure_depart: string;
  nb_nuits: number;
  prix_par_nuit: number;
  remise_montant: number;
  taxe_sejour_calculee?: number;
  options: ContratOptions;
  arrhes_montant: number;
  arrhes_date_limite: string;
  solde_montant: number;
  caution_montant: number;
  cheque_menage_montant: number;
  afficher_caution_phrase: boolean;
  afficher_cheque_menage_phrase: boolean;
  clauses: Record<string, unknown>;
  pdf_path: string;
  statut_paiement: "non_reglee" | "reglee";
  notes?: string | null;
  reservation_id?: string | null;
  gite?: Gite;
};
